import type { Metadata } from "next";
import Link from "next/link";
import { brand } from "@/config/brand";

export const metadata: Metadata = { title: "Terms of Service", description: `The terms that apply when you use ${brand.name}.` };

export default function TermsPage() {
  const { legal } = brand;
  return (
    <>
      <h1 className="text-[32px] font-bold leading-tight sm:text-[36px]">Terms of Service</h1>
      <p className="text-muted">Last updated: {legal.lastUpdated}</p>

      <p>
        These terms govern your use of {brand.name}, provided by {legal.entityName}. By creating an account or using the service, including
        the demo, you agree to them. Please also read our <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>The service</h2>
      <p>
        {brand.name} is a personal AI accountability assistant. It helps you set goals, plan your time and follow through, in the app and,
        if you opt in, by text message. Features may change as the product develops.
      </p>

      <h2>Eligibility and your account</h2>
      <ul>
        <li>You must be at least {legal.minimumAge} years old, and old enough to agree to these terms where you live.</li>
        <li>Keep your login details secure. You are responsible for activity on your account.</li>
        <li>Give accurate information, including a phone number that belongs to you if you enable text messages.</li>
      </ul>

      <h2>AI assistant — important limitations</h2>
      <ul>
        <li>The assistant&apos;s replies, plans and summaries are generated by AI and can be inaccurate or incomplete. Use your own judgment.</li>
        <li>
          {brand.name} is not a medical, mental-health, legal or financial service and does not provide professional advice. Consult a
          qualified professional for those needs.
        </li>
        <li>
          {brand.name} is not an emergency service. If you are in crisis or in danger, contact local emergency services or a crisis line
          immediately.
        </li>
      </ul>

      <h2>Text message program</h2>
      <p>
        If you add your mobile number and check the consent box, {brand.name} sends recurring accountability texts: check-ins, reminders
        about tasks you plan, and replies from your assistant. Message frequency varies. Message and data rates may apply. Reply{" "}
        <strong>STOP</strong> to cancel at any time and <strong>HELP</strong> for help, or contact{" "}
        <a href={`mailto:${brand.supportEmail}`}>{brand.supportEmail}</a>. Consent to texts is not a condition of using {brand.name}. Carriers
        are not liable for delayed or undelivered messages.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>break the law, or use the service to harass, harm or impersonate anyone;</li>
        <li>enter someone else&apos;s phone number, or send content you don&apos;t have the right to share;</li>
        <li>attempt to access other users&apos; data, probe or disrupt the service, or bypass usage limits;</li>
        <li>use automated means to create accounts, start demo sessions or send messages in bulk.</li>
      </ul>

      <h2>Your content</h2>
      <p>
        You own the goals, messages and other content you add. You give us permission to store and process it only to provide and improve
        the service for you, as described in the Privacy Policy.
      </p>

      <h2>Demo</h2>
      <p>The interactive demo uses sample data in a temporary account that may be reset or deleted at any time.</p>

      <h2>Ending your use</h2>
      <p>
        You can stop using {brand.name} and delete your account at any time in Settings. We may suspend or close accounts that violate these
        terms or put the service or other users at risk.
      </p>

      <h2>Disclaimers and limitation of liability</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without warranties of any kind, to the extent permitted by
        law. We don&apos;t guarantee that the service will be uninterrupted or error-free, or that you will achieve any particular result. To
        the extent permitted by law, {legal.entityName} is not liable for indirect, incidental or consequential damages arising from your use
        of the service.
      </p>

      {legal.governingLaw ? (
        <>
          <h2>Governing law</h2>
          <p>These terms are governed by the laws of {legal.governingLaw}.</p>
        </>
      ) : null}

      <h2>Changes to these terms</h2>
      <p>We may update these terms. If we make significant changes, we will let you know before they take effect.</p>

      <h2>Contact</h2>
      <p>
        {legal.entityName} — <a href={`mailto:${brand.supportEmail}`}>{brand.supportEmail}</a>
      </p>
    </>
  );
}
